### ISSUE TITLE
Enhancement ? Opacity slider ?

### ISSUE THREAD

**Issue by infuzz** [iamapig120/simple-color-picker#1]
Hello, your simple-color-picker is really great and super simple to use with no extra lib as promised in the readme. Thank you for that !
Do you think it could be hard to get an opacity slider option as enhancement ?
and obtain a rgba value as output rgba(r,g,b,opacity) ?

Regards, thierry

**Comment by iamapig120** [comment]
Received, I'll try it.
Thanks for your advice.

**Comment by iamapig120** [comment]
Sry I totally foget this repo...
I decide to rewrite this repo weeks ago and havnt finish yet...

**Comment by infuzz** [comment]
Hello, not an issue, Your work is great and it helps one year ago ! Since we have moved on [sveltejs](https://svelte.dev/) (react/vue killer fmk...) ( you should try it ! ) and we have used [svelte-color-picker](https://github.com/qintarp/svelte-color-picker) that is also great as yours was.

**Comment by iamapig120** [comment]
Yea I see, just keep this issue open to keep my enthusiasm

**Comment by iamapig120** [comment]
Sry for no more update. Busy for real life in college.
Also, your advice looks very great. Thx a lot, I might try later.
